EnterpriseSolution/EnterpriseSolution/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('projects/', include('app.urls')),
    path('admin/', admin.site.urls),
]

EnterpriseSolution/app/urls.py
from django.urls import path
from .views import ProjectDetailView, ProjectUpdateView, ProjectDeleteView,index, ProjectViewAll, CountryProjectViewAll, ProjectStatusViewAll,ProjectCreateView
app_name ="project"

urlpatterns = [
    # create a project
    path('create', ProjectCreateView.as_view(), name='create'),
    # view all projects 
    path('', index, name='index'),
    # view one project
    path('<pk>/', ProjectDetailView.as_view(), name='read'),
    # delete a project
    path('<pk>/delete', ProjectDeleteView.as_view(), name='delete'),
    # update a project
    path('<pk>/edit', ProjectUpdateView.as_view(), name='update'),

    # api urls
    path('api/projects/all', ProjectViewAll.as_view(), name='api-projects-all' ),
    path('api/projects/country/<str:country>', CountryProjectViewAll.as_view(), name='api-projects-country-all' ),
    path('api/projects/status/<str:status>', ProjectStatusViewAll.as_view(), name='api-projects-status-all' )
 
]

EnterpriseSolution/app/models.py
from django.db import models

    
class Office(models.Model):
    """
    implementation offices
    """
    implementation_office =models.CharField(max_length=100)
    # implementing_office_id

class Country(models.Model):
    """
    countries
    """
    country = models.CharField(max_length=100)
    # country_id
    
class Project(models.Model):
    """
    projects
    """
    project_ref = models.CharField(max_length=100)
    project_title = models.CharField(max_length=200)
    start_date = models.DateTimeField('start date')
    duration =  models.IntegerField(default=0)
    end_date = models.DateTimeField('end date')
    grant_amount = models.DecimalField(max_digits=20, decimal_places=2)
    first_disbursement_amount = models.DecimalField(max_digits=20, decimal_places=2)
    readiness_or_NAP =models.CharField(max_length=100)
    types_of_readiness = models.CharField(max_length=100)
    status = models.CharField(max_length=100,blank=True)


class ProjectImplementation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)
    implementation_office = models.ForeignKey(Office, on_delete=models.PROTECT)

EnterpriseSolution/app/views.py
# django imports
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.core.paginator import Paginator

# rest framework
from rest_framework.generics import ListAPIView

# local imports
from .serializer import ProjectImplementationSerializer, ProjectSerializer
from .models import Project,ProjectImplementation

#  index page view all projects(get)
def index(request):
    # if request.method == "POST":
    #     project_list = Project.objects.all()[:int(request.POST.get("show_records"))]
    #     context = {'project_list': project_list}
    #     return render(request, 'app/index.html', context)
    if request.method == "POST":
        records = int(request.POST.get("show_records"))
        project_list = Project.objects.all()[:records]
        page_obj = Paginator(project_list, records)
        context = {'project_list': project_list, 'page_obj': page_obj}
        return render(request, 'app/index.html', context)
    else:
        project_list = Project.objects.all()[:10]
        context = {'project_list': project_list}
        return render(request, 'app/index.html', context)

# create a project
class ProjectCreateView(CreateView):
    model = Project
    fields = '__all__'

    def get_success_url(self) -> str:
        success_url = reverse_lazy('project:index')
        return success_url

# view a single project
class ProjectDetailView(DetailView):
    model = Project
    fields = '__all__'

# update a project
class ProjectUpdateView(UpdateView):
    model = Project
    fields = '__all__'
    
    def get_success_url(self) -> str:
        projectid = self.kwargs['pk']
        success_url = reverse_lazy('project:read', kwargs={'pk':projectid})
        return success_url

# delete a project
class ProjectDeleteView(DeleteView):
    model=Project

    def get_success_url(self) -> str:
        success_url = reverse_lazy('project:index')
        return success_url

# API 
# get all projects
class ProjectViewAll(ListAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = "pk"

# get projects based on a country
class CountryProjectViewAll(ListAPIView):
    queryset = ProjectImplementation.objects.all()
    serializer_class = ProjectImplementationSerializer

    def get_queryset(self):
        country = self.kwargs.get('country',None)
        if country:
            return ProjectImplementation.objects.filter(country_id__country=country).all()
        return ProjectImplementation.objects.all()

    

# get projects based on the status
class ProjectStatusViewAll(ListAPIView):
    quesyset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = "pk"
    

    def get_queryset(self):
        status = self.kwargs.get('status',None)
        if status:
            return Project.objects.filter(status=status).all()
        return Project.objects.all()

    

EnterpriseSolution/app/templates/app/index.html
{% extends "base.html" %}
{% block content %}
<h2>PROJECTS</h2>
<a type="button" href="{% url 'project:create' %}">ADD PROJECT</a>
<form method="POST">
{% csrf_token %}
<select name="show_records">
  <option disabled selected="true">--select--</option>
  <option>5</option>
  <option>10</option>
  <option>15</option>
  <option>20</option>
  <option>25</option>
  <option>30</option>
  <option>40</option>
  <option>50</option>
  <option>60</option>
  <option>70</option>
  <option>80</option>
  <option>90</option>
  <option>100</option>
</select>
<button type="submit">show records</button>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Project REF</th>
      <th scope="col">Project Title</th>
      <th scope="col">modify<th>
    </tr>
</thead>
{% if project_list %}
{% for project in project_list %}
<tbody>

  <tr>
    <th scope="row">{{project.id}}</th>
    <td>{{ project.project_ref }}</td>
    <td>{{ project.project_title }}</td>
    <td>
      <div class="btn-group">
        <a type="button" class="btn btn-primary btn-sm"  href="/projects/{{ project.id }}/">VIEW</a>
        <a type="button" class="btn btn-warning btn-sm" href="/projects/{{ project.id }}/edit">EDIT</a>
        <a type="button" class="btn btn-danger btn-sm" href="/projects/{{ project.id }}/delete">DELETE</a>
      </div>
    </td>
  </tr>
</tbody>
  {% endfor %}
  {% else %}
  <p>No projects available.</p>
  {% endif %}
</table>
</form>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

     
      
      <span class="current">

          Page {{ page_obj.num_pages }} of {{ page_obj.last_page }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>


{% endblock %}

EnterpriseSolution/app/templates/app/project_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Project</h1>

        <p class="h5">Are you sure you want to delete the Project: "{{project.project_ref}}"</p>
        <h3 class="my-5">{{ project.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url '' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'project:index' %}'; return false;" value="Cancel">
        </form>
            

  </div>

  {% endblock %}

EnterpriseSolution/app/templates/app/project_detail.html
{% extends "base.html" %}
{% block content %}

<div class="col">
    <h1 class="text-center">Project Details</h1>
    <div class="d-flex justify-content-center">
        <div>
            <p>Project Title: {{ project.project_title }}</p>
            <p>Project REF: {{ project.project_ref }}</p>
            <p>Start Date: {{ project.start_date }}</p>
            <p>Duration: {{ project.duration}}</p>
            <p>End Date: {{ project.end_date }}</p>
            <p>Grant Amount: {{ project.grant_amount}}</p>
            <p>First disbursement amount: {{ project.first_disbursement_amount }}</p>
            <p>Readiness or NAP: {{ project.readiness_or_NAP }}</p>
            <p>Types of readiness: {{ project.types_of_readiness }}</p>
            <p>Status: {{ project.status }}</p>
        </div>
    </div>

    <div class="d-flex justify-content-center">
        <a href="{% url 'project:index' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
    </div>
</div>



{% endblock %}

EnterpriseSolution/app/templates/app/project_form.html
{% extends "base.html" %}
{% block content %}
</br>
<div class="d-flex justify-content-center">
    <h5>Create or Edit a Project below:</h5>
</div>
 <div class="d-flex justify-content-center">
   
    </br>
    <form style="width: 50%; justify: center;" method="POST" action="">
        {% csrf_token %}
        <table class="table">
            {{form.as_table}}
        </table>
        <button type="submit"  class="btn btn-primary">Submit</button>
        <button type="submit" onclick="window.location='{% url 'project:index' %}'; return false;" value="Cancel" class="btn btn-warning">cancel</button>
        </div>
      </form>
</div>

{% endblock %}

EnterpriseSolution/app/templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | PROJECTS</title> 
    {% else %}
        <title>Projects Table</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>


<nav class="navbar navbar-expand-sm bg-dark">

        <div class="container-fluid">
          <!-- Links -->
          <span class="navbar-text text-white"><h4>ENTERPRISE SOLUTION</h4></span>

        </div>
      
</nav>
<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>